# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\软件\github\onmyoji_bot\onmyoji.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(545, 700)
        MainWindow.setMinimumSize(QtCore.QSize(545, 590))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setEnabled(True)
        self.textEdit.setMinimumSize(QtCore.QSize(216, 124))
        self.textEdit.setStatusTip("")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.start_btn = QtWidgets.QPushButton(self.frame)
        self.start_btn.setMinimumSize(QtCore.QSize(246, 23))
        self.start_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout_2.addWidget(self.start_btn)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(246, 0))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.mitama_single = QtWidgets.QRadioButton(self.groupBox)
        self.mitama_single.setAutoFillBackground(False)
        self.mitama_single.setChecked(True)
        self.mitama_single.setObjectName("mitama_single")
        self.gridLayout.addWidget(self.mitama_single, 0, 0, 1, 1)
        self.mitama_driver = QtWidgets.QRadioButton(self.groupBox)
        self.mitama_driver.setObjectName("mitama_driver")
        self.gridLayout.addWidget(self.mitama_driver, 0, 1, 1, 1)
        self.mitama_passenger = QtWidgets.QRadioButton(self.groupBox)
        self.mitama_passenger.setObjectName("mitama_passenger")
        self.gridLayout.addWidget(self.mitama_passenger, 1, 0, 1, 1)
        self.mitama_dual = QtWidgets.QRadioButton(self.groupBox)
        self.mitama_dual.setObjectName("mitama_dual")
        self.gridLayout.addWidget(self.mitama_dual, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_1.setChecked(True)
        self.radioButton_1.setObjectName("radioButton_1")
        self.gridLayout_9.addWidget(self.radioButton_1, 0, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_9.addWidget(self.radioButton_3, 1, 0, 1, 2)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_9.addWidget(self.radioButton_2, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.tab_4)
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.verticalLayout_3.addWidget(self.plainTextEdit_3)
        self.tabWidget.addTab(self.tab_4, "")

        # 探索
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2_2.setObjectName("gridLayout_2_2")
        self.groupBox_2_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2_2.setObjectName("groupBox_2_2")
        self.gridLayout_explore = QtWidgets.QGridLayout(self.groupBox_2_2)
        self.gridLayout_explore.setObjectName("gridLayout_explore")
        self.explore_single = QtWidgets.QRadioButton(self.groupBox_2_2)
        self.explore_single.setAutoFillBackground(False)
        self.explore_single.setChecked(False)
        self.explore_single.setObjectName("explore_single")
        self.gridLayout_explore.addWidget(self.explore_single, 0, 0, 1, 1)
        self.explore_driver = QtWidgets.QRadioButton(self.groupBox_2_2)
        self.explore_driver.setObjectName("explore_driver")
        self.gridLayout_explore.addWidget(self.explore_driver, 0, 1, 1, 1)
        self.explore_passenger = QtWidgets.QRadioButton(self.groupBox_2_2)
        self.explore_passenger.setObjectName("explore_passenger")
        self.gridLayout_explore.addWidget(self.explore_passenger, 1, 0, 1, 1)
        self.explore_dual = QtWidgets.QRadioButton(self.groupBox_2_2)
        self.explore_dual.setObjectName("explore_dual")
        self.explore_dual.setChecked(True)
        self.gridLayout_explore.addWidget(self.explore_dual, 1, 1, 1, 1)
        self.gridLayout_2_2.addWidget(self.groupBox_2_2, 0, 0, 1, 1)

        self.groupBox_2_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2_3.setObjectName("groupBox_2_3")
        self.gridLayout_2_3 = QtWidgets.QGridLayout(self.groupBox_2_3)
        self.gridLayout_2_3.setObjectName("gridLayout_2_3")
        self.explore_ka_1 = QtWidgets.QRadioButton(self.groupBox_2_3)
        self.explore_ka_1.setChecked(True)
        self.explore_ka_1.setObjectName("explore_ka_1")
        self.gridLayout_2_3.addWidget(self.explore_ka_1, 0, 0, 1, 1)
        self.explore_ka_2 = QtWidgets.QRadioButton(self.groupBox_2_3)
        self.explore_ka_2.setObjectName("explore_ka_2")
        self.gridLayout_2_3.addWidget(self.explore_ka_2, 1, 0, 1, 2)
        self.explore_ka_3 = QtWidgets.QRadioButton(self.groupBox_2_3)
        self.explore_ka_3.setObjectName("explore_ka_3")
        self.gridLayout_2_3.addWidget(self.explore_ka_3, 0, 2, 1, 1)
        self.gridLayout_2_2.addWidget(self.groupBox_2_3, 1, 0, 1, 1)


        self.groupBox_2_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2_4.setObjectName("groupBox_2_4")
        self.gridLayout_2_4 = QtWidgets.QGridLayout(self.groupBox_2_4)
        self.gridLayout_2_4.setObjectName("gridLayout_2_4")
        self.checkBox_driver_gouliang1 = QtWidgets.QCheckBox(self.groupBox_2_4)
        # self.checkBox_driver_gouliang1.setChecked(True)
        self.checkBox_driver_gouliang1.setObjectName("checkBox_driver_gouliang1")
        self.gridLayout_2_4.addWidget(self.checkBox_driver_gouliang1, 0, 0, 1, 1)
        self.checkBox_driver_gouliang2 = QtWidgets.QCheckBox(self.groupBox_2_4)
        # self.checkBox_driver_gouliang2.setChecked(True)
        self.checkBox_driver_gouliang2.setObjectName("checkBox_driver_gouliang2")
        self.gridLayout_2_4.addWidget(self.checkBox_driver_gouliang2, 0, 1, 1, 1)
        self.gridLayout_2_2.addWidget(self.groupBox_2_4, 2, 0, 1, 1)
        #
        self.groupBox_2_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2_5.setObjectName("groupBox_2_5")
        self.gridLayout_2_5 = QtWidgets.QGridLayout(self.groupBox_2_5)
        self.gridLayout_2_5.setObjectName("gridLayout_2_5")
        self.checkBox_passenger_gouliang1 = QtWidgets.QCheckBox(self.groupBox_2_5)
        self.checkBox_passenger_gouliang1.setChecked(True)
        self.checkBox_passenger_gouliang1.setObjectName("checkBox_passenger_gouliang1")
        self.gridLayout_2_5.addWidget(self.checkBox_passenger_gouliang1, 0, 0, 1, 1)

        self.checkBox_passenger_gouliang3 = QtWidgets.QCheckBox(self.groupBox_2_5)
        self.checkBox_passenger_gouliang3.setChecked(True)
        self.checkBox_passenger_gouliang3.setObjectName("checkBox_passenger_gouliang3")
        self.gridLayout_2_5.addWidget(self.checkBox_passenger_gouliang3, 0, 1, 1, 1)

        self.checkBox_passenger_gouliang2 = QtWidgets.QCheckBox(self.groupBox_2_5)
        self.checkBox_passenger_gouliang2.setChecked(True)
        self.checkBox_passenger_gouliang2.setObjectName("checkBox_passenger_gouliang2")
        self.gridLayout_2_5.addWidget(self.checkBox_passenger_gouliang2, 0, 2, 1, 1)
        self.gridLayout_2_2.addWidget(self.groupBox_2_5, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")

        # self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        # self.gridLayout_5.setObjectName("gridLayout_5")
        # self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        # self.groupBox_5.setObjectName("groupBox_5")
        # self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        # self.checkBox_2 = QtWidgets.QCheckBox(self.tab_2)
        # self.checkBox_2.setObjectName("checkBox_2")
        # self.gridLayout_5.addWidget(self.checkBox_2, 6, 0, 1, 1)


        # 突破
        self.tab_tu = QtWidgets.QWidget()
        self.tab_tu.setObjectName("tab_tu")
        self.gridLayout_tu = QtWidgets.QGridLayout(self.tab_tu)
        self.gridLayout_tu.setObjectName("gridLayout_tu")

        self.groupBox_tu_1 = QtWidgets.QGroupBox(self.tab_tu)
        self.groupBox_tu_1.setObjectName("groupBox_tu_1")
        self.gridLayout_tu_1 = QtWidgets.QGridLayout(self.groupBox_tu_1)
        self.gridLayout_tu_1.setObjectName("gridLayout_tu_1")

        self.tu_auto = QtWidgets.QRadioButton(self.groupBox_tu_1)
        self.tu_auto.setAutoFillBackground(False)
        self.tu_auto.setChecked(True)
        self.tu_auto.setObjectName("tu_auto")
        self.gridLayout_tu_1.addWidget(self.tu_auto, 0, 0, 0, 1)

        self.tu_shoudong = QtWidgets.QRadioButton(self.groupBox_tu_1)
        self.tu_shoudong.setObjectName("tu_shoudong")
        self.gridLayout_tu_1.addWidget(self.tu_shoudong, 0, 1, 0, 1)
        self.gridLayout_tu.addWidget(self.groupBox_tu_1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_tu, "")




        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_4.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")

        self.verticalLayout.addWidget(self.tabWidget)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 4, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_7.addWidget(self.checkBox, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_7.addWidget(self.lineEdit, 3, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_7.addWidget(self.lineEdit_2, 4, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_7.addWidget(self.checkBox_4, 0, 0, 1, 1)

        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_7.addWidget(self.checkBox_5, 5, 0, 1, 1)

        self.comboBox_1 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItems(["第一个式神", "第二个式神", "第三个式神", "第四个式神","第五个式神"])
        self.gridLayout_7.addWidget(self.comboBox_1, 5, 1, 1, 1)

        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_7.addWidget(self.checkBox_6, 6, 0, 1, 1)


        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 545, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionAbout_2 = QtWidgets.QAction(MainWindow)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setStatusTip("")
        self.actionAbout.setObjectName("actionAbout")
        self.menu.addAction(self.actionAbout)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.start_btn.clicked.connect(MainWindow.start_onmyoji)
        self.pushButton.clicked.connect(MainWindow.stop_onmyoji)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "onmyoji_bot"))
        self.label_4.setText(_translate("MainWindow", "日志"))
        self.start_btn.setText(_translate("MainWindow", "开始"))
        self.pushButton.setText(_translate("MainWindow", "结束"))
        self.label.setText(_translate("MainWindow", "辅助助手"))
        self.groupBox.setTitle(_translate("MainWindow", "模式"))
        self.mitama_single.setText(_translate("MainWindow", "单刷"))
        self.mitama_driver.setText(_translate("MainWindow", "单人司机"))
        self.mitama_passenger.setText(_translate("MainWindow", "单人乘客"))
        self.mitama_dual.setText(_translate("MainWindow", "双开"))
        self.groupBox_4.setTitle(_translate("MainWindow", "副本(调试中)"))
        self.radioButton_1.setText(_translate("MainWindow", "八岐大蛇"))
        self.radioButton_3.setText(_translate("MainWindow", "卑弥呼"))
        self.radioButton_2.setText(_translate("MainWindow", "业原火"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "御魂"))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "选择好要打的御灵及层数，点击开始按钮即可。"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "御灵"))


        # self.checkBox_2.setText(_translate("MainWindow", "结束后打BOSS"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "探索"))
        self.groupBox_2_2.setTitle(_translate("MainWindow", "模式"))
        self.explore_single.setText(_translate("MainWindow", "单刷"))
        self.explore_driver.setText(_translate("MainWindow", "单人司机"))
        self.explore_passenger.setText(_translate("MainWindow", "单人乘客"))
        self.explore_dual.setText(_translate("MainWindow", "双开"))
        self.groupBox_2_3.setTitle(_translate("MainWindow", "狗粮类型"))
        self.explore_ka_1.setText(_translate("MainWindow", "N卡"))
        self.explore_ka_2.setText(_translate("MainWindow", "白蛋"))
        self.explore_ka_3.setText(_translate("MainWindow", "R卡"))
        self.groupBox_2_4.setTitle(_translate("MainWindow", "司机狗粮位置"))
        self.checkBox_driver_gouliang1.setText(_translate("MainWindow", "一号"))
        self.checkBox_driver_gouliang2.setText(_translate("MainWindow", "三号"))
        self.groupBox_2_5.setTitle(_translate("MainWindow", "打手狗粮位置"))
        self.checkBox_passenger_gouliang1.setText(_translate("MainWindow", "一号"))
        self.checkBox_passenger_gouliang2.setText(_translate("MainWindow", "二号"))
        self.checkBox_passenger_gouliang3.setText(_translate("MainWindow", "三号"))

        self.plainTextEdit.setPlainText(_translate("MainWindow", "网址：https://github.com/AcademicDog/onmyoji_bot\n"
"\n"
"交流Q群：592055060"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "关于"))

        # self.plainTextEdit_tu.setPlainText(_translate("MainWindow", "自动突破，建议选择下方标记己方式神"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tu), _translate("MainWindow", "突破"))

        self.groupBox_tu_1.setTitle(_translate("MainWindow", "模式"))
        self.tu_auto.setText(_translate("MainWindow", "自动战斗"))
        self.tu_shoudong.setText(_translate("MainWindow", "手动战斗"))

        self.groupBox_2.setTitle(_translate("MainWindow", "高级选项"))
        self.label_2.setText(_translate("MainWindow", "  画面超时时间(秒)："))
        self.label_3.setText(_translate("MainWindow", "  操作超时时间(秒)："))
        self.checkBox.setText(_translate("MainWindow", "超时自动关闭阴阳师"))
        self.lineEdit.setText(_translate("MainWindow", "100"))
        self.lineEdit_2.setText(_translate("MainWindow", "20"))
        self.checkBox_4.setText(_translate("MainWindow", "调试模式"))
        self.checkBox_5.setText(_translate("MainWindow", "标记式神"))
        self.checkBox_6.setText(_translate("MainWindow", "是否点怪"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.actionAbout_2.setText(_translate("MainWindow", "About"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

